backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: 'images' # Media files will be stored in the repo under images

collections:
  - name: 'pages' # Used in routes, e.g., /admin/collections/blog
    label: 'Pages' # Used in the UI
    folder: 'pages' # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Header', name: 'header', widget: 'string' }
      - { label: 'SubHeader', name: 'subheader', widget: 'string' }